version: "3.8"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql_${MYSQL_VERSION}
    ports:
      - ${REAL_MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_DIR}/data:/var/lib/mysql
      - ${MYSQL_DIR}/my.cnf:/etc/mysql/my.conf
      - ${MYSQL_DIR}/logs:/logs
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    restart: always
